# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy

class RentalInfo(scrapy.Item):
    title = scrapy.Field()
    url = scrapy.Field()
    image = scrapy.Field()
    address = scrapy.Field()
    warmmiete = scrapy.Field()
    kaltmiete = scrapy.Field()
    nebenkosten = scrapy.Field()
    kaution = scrapy.Field()
    area = scrapy.Field()
    num_rooms = scrapy.Field()
    facts = scrapy.Field()

class WgGesuchtItem(RentalInfo):
    sonstige_kosten  = scrapy.Field()
    abloesevereinbarung = scrapy.Field()
    from_date = scrapy.Field()
    to_date = scrapy.Field()
    online_since = scrapy.Field()
    text_wohnung = scrapy.Field()
    text_lage = scrapy.Field()
    text_sonstiges = scrapy.Field()

class WgGesuchtItemCheck(WgGesuchtItem):
    check=scrapy.Field()

class ImmoscoutItem(RentalInfo):
    heizkosten = scrapy.Field()
    miete_garage_stellplatz = scrapy.Field()
    text_summary = scrapy.Field()
    text_description = scrapy.Field()
    text_ausstattung = scrapy.Field()
    text_lage = scrapy.Field()
    text_sonstiges = scrapy.Field()


class ImmoweltItem(RentalInfo):
    keywords = scrapy.Field()
    heizkosten = scrapy.Field()
    parking = scrapy.Field()
    building_year = scrapy.Field()
    text_summary = scrapy.Field()
    text_description = scrapy.Field()
    text_ausstattung = scrapy.Field()
    text_lage = scrapy.Field()
    text_sonstiges = scrapy.Field()
    online_id = scrapy.Field()

class RentalInfoAPI(scrapy.Item):
    site = scrapy.Field()
    title = scrapy.Field()
    url = scrapy.Field()
    image = scrapy.Field()
    property_type = scrapy.Field()
    warmmiete = scrapy.Field()
    kaltmiete = scrapy.Field()
    nebenkosten = scrapy.Field()
    heizungskosten = scrapy.Field()
    kaution = scrapy.Field()
    area = scrapy.Field()
    num_rooms = scrapy.Field()
    address = scrapy.Field()
    postcode = scrapy.Field()
    geo_latitude = scrapy.Field()
    geo_longitude = scrapy.Field()
    offer_id= scrapy.Field()
    balcony = scrapy.Field()
    energy_building_year = scrapy.Field()
    kitchen_availability = scrapy.Field()
    cellar = scrapy.Field()
    pets_allowed = scrapy.Field()
    energy_efficiency_class = scrapy.Field()
    energy_consumption = scrapy.Field()
    elevator = scrapy.Field()
    floor_level = scrapy.Field()
    garden = scrapy.Field()
    handicap_accessible = scrapy.Field()
    freetext_property_description = scrapy.Field()
    freetext_area_description = scrapy.Field()
    freetext_other = scrapy.Field()
    heating = scrapy.Field()
    preis_qm_kalt = scrapy.Field()
    available_from_date = scrapy.Field()

class WgGesuchtItemAPI(RentalInfoAPI):
    available_to_date= scrapy.Field()
    green_energy= scrapy.Field()
    dishwasher= scrapy.Field()
    washing_machine= scrapy.Field()
    bath= scrapy.Field()
    shower= scrapy.Field()
    guest_toilet= scrapy.Field()
    bath_availability= scrapy.Field()
    terrace= scrapy.Field()
    shared_garden= scrapy.Field()
    attic= scrapy.Field()
    bike_cellar= scrapy.Field()
    parking_option= scrapy.Field()
    carpet= scrapy.Field()
    parquet= scrapy.Field()
    laminate= scrapy.Field()
    floorboards= scrapy.Field()
    linoleum= scrapy.Field()
    tiles= scrapy.Field()
    underfloor_heating= scrapy.Field()
    cable_tv= scrapy.Field()
    satellite_tv= scrapy.Field()
    phone_analog= scrapy.Field()
    phone_isdn= scrapy.Field()
    phone_voip= scrapy.Field()
    phone_flatrate= scrapy.Field()
    internet_dsl= scrapy.Field()
    internet_flatrate= scrapy.Field()
    internet_wlan= scrapy.Field()
    internet_dsl_speed= scrapy.Field()
    internet_provider_change= scrapy.Field()
    furnished= scrapy.Field()
    flatshare_friendly= scrapy.Field()
    online_tour= scrapy.Field()
    offer_in_exchange= scrapy.Field()
    partly_furnished= scrapy.Field()
    smoking_is_allowed= scrapy.Field()
    public_transport_in_minutes= scrapy.Field()
    energy_certificate_type= scrapy.Field()
    energy_source= scrapy.Field()

class ImmoscoutItemAPI(RentalInfoAPI):
    freetext_ausstattung = scrapy.Field()